project:
  type: website

website:
  title: "Carolyn Petree's WebGIS Site"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: map.qmd
        text: Map
      - href: data.qmd
        text: Data
      - href: openletter.qmd
        text: Open Letter

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

